USE [Hauswirtschaft_Center_DB]
GO
/****** Object:  Table [dbo].[CONFIG]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HausPflichtAktiv] [bit] NULL,
 CONSTRAINT [PK_EXTRAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ERFASSER]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ERFASSER](
	[ErfasserID] [int] IDENTITY(1000,1) NOT NULL,
	[Erfasser] [nvarchar](50) NULL,
	[Telefon] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Inaktiv] [bit] NOT NULL,
	[DomUser] [nvarchar](50) NULL,
	[RollenID] [int] NULL,
	[Del] [bit] NULL,
	[DelDate] [datetime] NULL,
 CONSTRAINT [PK_ERFASSER] PRIMARY KEY CLUSTERED 
(
	[ErfasserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ETAGE]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ETAGE](
	[EtagenID] [int] IDENTITY(1,1) NOT NULL,
	[ObjektID] [int] NULL,
	[EtagenName] [nvarchar](100) NULL,
 CONSTRAINT [PK_ETAGE] PRIMARY KEY CLUSTERED 
(
	[EtagenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FEHLERKATEGORIE]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEHLERKATEGORIE](
	[FehlerKategorieID] [int] IDENTITY(1,1) NOT NULL,
	[Fehlerkategorie] [nvarchar](50) NULL,
 CONSTRAINT [PK_FEHLERKATEGORIE] PRIMARY KEY CLUSTERED 
(
	[FehlerKategorieID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OBJEKT]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OBJEKT](
	[ObjektID] [int] IDENTITY(1,1) NOT NULL,
	[ObjektName] [nvarchar](100) NULL,
 CONSTRAINT [PK_OBJEKT] PRIMARY KEY CLUSTERED 
(
	[ObjektID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONALBEREICH]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONALBEREICH](
	[PersBereichID] [int] IDENTITY(1,1) NOT NULL,
	[Personalbereich] [nvarchar](50) NULL,
 CONSTRAINT [PK_PERSONALBEREICH] PRIMARY KEY CLUSTERED 
(
	[PersBereichID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLLE]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Rolle] [nvarchar](50) NULL,
	[Del] [bit] NULL,
	[DelDate] [datetime] NULL,
 CONSTRAINT [PK_ROLLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPORT]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPORT](
	[SupportID] [int] IDENTITY(20000,1) NOT NULL,
	[FehlerKategorieID] [int] NULL,
	[PersBereichID] [int] NULL,
	[ErfasserID] [int] NULL,
	[TextID] [int] NULL,
	[Falltitel] [nvarchar](50) NULL,
	[Fallname] [nvarchar](50) NULL,
	[Erfassungsdatum] [datetime] NULL,
	[Erfasser] [nvarchar](50) NULL,
	[Problemschilderung] [ntext] NULL,
	[PlandatumBearbeitung] [datetime] NULL,
	[Plandauer] [float] NULL,
	[Dauereinheit] [nvarchar](50) NULL,
	[Bearbeitungsdatum] [datetime] NULL,
	[Erledigt] [bit] NOT NULL,
	[Weiterbearbeitungsdatum] [datetime] NULL,
	[Istdauer] [float] NULL,
	[Legende] [ntext] NULL,
	[ObjektID] [int] NULL,
	[EtagenID] [int] NULL,
	[ZimmerID] [int] NULL,
	[Ursache] [ntext] NULL,
	[ZugErfasser] [int] NULL,
 CONSTRAINT [PK_SUPPORT] PRIMARY KEY CLUSTERED 
(
	[SupportID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TEXT]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TEXT](
	[TextID] [int] IDENTITY(1,1) NOT NULL,
	[Text] [text] NULL,
	[Bemerkung] [nvarchar](100) NULL,
 CONSTRAINT [PK_TEXT] PRIMARY KEY CLUSTERED 
(
	[TextID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZIMMER]    Script Date: 14.12.2023 22:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZIMMER](
	[ZimmerID] [int] IDENTITY(1,1) NOT NULL,
	[EtagenID] [int] NULL,
	[Zimmer] [nvarchar](100) NULL,
	[ZimmerNr] [int] NULL,
	[ZimmerNrText] [nvarchar](50) NULL,
 CONSTRAINT [PK_ZIMMER] PRIMARY KEY CLUSTERED 
(
	[ZimmerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERFASSER] ADD  CONSTRAINT [DF_ERFASSER_Inaktiv]  DEFAULT ((0)) FOR [Inaktiv]
GO
ALTER TABLE [dbo].[ETAGE] ADD  CONSTRAINT [DF_ETAGE_EtagenName]  DEFAULT (N'Etage') FOR [EtagenName]
GO
ALTER TABLE [dbo].[SUPPORT] ADD  CONSTRAINT [DF_SUPPORT_Plandauer]  DEFAULT ((0)) FOR [Plandauer]
GO
ALTER TABLE [dbo].[SUPPORT] ADD  CONSTRAINT [DF_SUPPORT_Dauereinheit]  DEFAULT (N'Stunde(n)') FOR [Dauereinheit]
GO
ALTER TABLE [dbo].[SUPPORT] ADD  CONSTRAINT [DF_SUPPORT_Erledigt]  DEFAULT ((0)) FOR [Erledigt]
GO
ALTER TABLE [dbo].[ZIMMER] ADD  CONSTRAINT [DF_ZIMMER_Zimmer]  DEFAULT (N'Zimmer') FOR [Zimmer]
GO
ALTER TABLE [dbo].[ETAGE]  WITH CHECK ADD  CONSTRAINT [FK_ETAGE_OBJEKT] FOREIGN KEY([ObjektID])
REFERENCES [dbo].[OBJEKT] ([ObjektID])
GO
ALTER TABLE [dbo].[ETAGE] CHECK CONSTRAINT [FK_ETAGE_OBJEKT]
GO
ALTER TABLE [dbo].[SUPPORT]  WITH CHECK ADD  CONSTRAINT [FK_SUPPORT_ERFASSER] FOREIGN KEY([ErfasserID])
REFERENCES [dbo].[ERFASSER] ([ErfasserID])
GO
ALTER TABLE [dbo].[SUPPORT] CHECK CONSTRAINT [FK_SUPPORT_ERFASSER]
GO
ALTER TABLE [dbo].[SUPPORT]  WITH CHECK ADD  CONSTRAINT [FK_SUPPORT_FEHLERKATEGORIE] FOREIGN KEY([FehlerKategorieID])
REFERENCES [dbo].[FEHLERKATEGORIE] ([FehlerKategorieID])
GO
ALTER TABLE [dbo].[SUPPORT] CHECK CONSTRAINT [FK_SUPPORT_FEHLERKATEGORIE]
GO
ALTER TABLE [dbo].[SUPPORT]  WITH CHECK ADD  CONSTRAINT [FK_SUPPORT_PERSONALBEREICH] FOREIGN KEY([PersBereichID])
REFERENCES [dbo].[PERSONALBEREICH] ([PersBereichID])
GO
ALTER TABLE [dbo].[SUPPORT] CHECK CONSTRAINT [FK_SUPPORT_PERSONALBEREICH]
GO
ALTER TABLE [dbo].[SUPPORT]  WITH CHECK ADD  CONSTRAINT [FK_SUPPORT_TEXT1] FOREIGN KEY([TextID])
REFERENCES [dbo].[TEXT] ([TextID])
GO
ALTER TABLE [dbo].[SUPPORT] CHECK CONSTRAINT [FK_SUPPORT_TEXT1]
GO
ALTER TABLE [dbo].[ZIMMER]  WITH CHECK ADD  CONSTRAINT [FK_ZIMMER_ETAGE] FOREIGN KEY([EtagenID])
REFERENCES [dbo].[ETAGE] ([EtagenID])
GO
ALTER TABLE [dbo].[ZIMMER] CHECK CONSTRAINT [FK_ZIMMER_ETAGE]
GO