USE [Technik_Center_DB] 

GO 

/****** Object:  Table [dbo].[PERSONALBEREICH_ERFASSER] ******/ 

SET ANSI_NULLS ON 
GO 

SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[PERSONALBEREICH_ERFASSER]( 
	[ErfassserID] [int] NOT NULL, 
	[PersBereichID] [int] NOT NULL, 
	[RolleID] [int] NOT NULL, 
CONSTRAINT [PK__PERSONAL__DC02FF1D3AA6B33D] PRIMARY KEY CLUSTERED  
( 
	[ErfassserID] ASC, 
	[PersBereichID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] 
) ON [PRIMARY] 
GO 

ALTER TABLE [dbo].[PERSONALBEREICH_ERFASSER]  WITH CHECK ADD  CONSTRAINT [FK__PERSONALB__PersB__634EBE90] FOREIGN KEY([PersBereichID]) 
REFERENCES [dbo].[PERSONALBEREICH] ([PersBereichID]) 
GO 

ALTER TABLE [dbo].[PERSONALBEREICH_ERFASSER] CHECK CONSTRAINT [FK__PERSONALB__PersB__634EBE90] 
GO 

ALTER TABLE [dbo].[PERSONALBEREICH_ERFASSER]  WITH CHECK ADD  CONSTRAINT [FK_PERSONALBEREICH_ERFASSER_ERFASSER] FOREIGN KEY([ErfassserID]) 
REFERENCES [dbo].[ERFASSER] ([ErfasserID]) 
GO 

ALTER TABLE [dbo].[PERSONALBEREICH_ERFASSER] CHECK CONSTRAINT [FK_PERSONALBEREICH_ERFASSER_ERFASSER] 
GO 

ALTER TABLE [dbo].[PERSONALBEREICH_ERFASSER]  WITH CHECK ADD  CONSTRAINT [FK_PERSONALBEREICH_ERFASSER_ROLLE] FOREIGN KEY([RolleID]) 
REFERENCES [dbo].[ROLLE] ([ID]) 
GO 

ALTER TABLE [dbo].[PERSONALBEREICH_ERFASSER] CHECK CONSTRAINT [FK_PERSONALBEREICH_ERFASSER_ROLLE] 
GO 